USE mod3;
DROP TABLE IF EXISTS  Installer;
DROP TABLE IF EXISTS  Logiciel;
DROP TABLE IF EXISTS  Poste;
DROP TABLE IF EXISTS  Types;
DROP TABLE IF EXISTS  Salle;
DROP TABLE IF EXISTS  Segment;
